# Form implementation generated from reading ui file '..\Gui\MojeUI2.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1186, 727)
        MainWindow.setMinimumSize(QtCore.QSize(940, 560))
        self.styleSheet = QtWidgets.QWidget(parent=MainWindow)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.styleSheet.setFont(font)
        self.styleSheet.setStyleSheet("QWidget{\n"
"    color: rgb(221, 221, 221);\n"
"    font: 700 12pt \"Segoe Print\";\n"
"}\n"
"QTableWidget {\n"
"    background-color: transparent;\n"
"    padding: 10px;\n"
"    border-radius: 5px;\n"
"    gridline-color: rgb(44, 49, 58);\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item{\n"
"    border-color: rgb(44, 49, 60);\n"
"    padding-left: 5px;\n"
"    padding-right: 5px;\n"
"    gridline-color: rgb(44, 49, 60);\n"
"}\n"
"QTableWidget::item:selected{\n"
"    background-color: rgb(189, 147, 249);\n"
"}\n"
"QTableWidget::horizontalHeader {\n"
"    background-color: rgb(33, 37, 43);\n"
"}\n"
"QHeaderView::section{\n"
"    background-color: rgb(33, 37, 43);\n"
"    max-width: 30px;\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"    border-style: none;\n"
"    border-bottom: 1px solid rgb(44, 49, 60);\n"
"    border-right: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QHeaderView::section:horizontal\n"
"{\n"
"    border: 1px solid rgb(33, 37, 43);\n"
"    background-color: rgb(33, 37, 43);\n"
"    padding: 3px;\n"
"    border-top-left-radius: 7px;\n"
"    border-top-right-radius: 7px;\n"
"}\n"
"QHeaderView::section:vertical\n"
"{\n"
"    border: 1px solid rgb(44, 49, 60);\n"
"}\n"
"QLineEdit {\n"
"    background-color: rgb(33, 37, 43);\n"
"    border-radius: 5px;\n"
"    border: 2px solid rgb(33, 37, 43);\n"
"    padding-left: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"}\n"
"QLineEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QLineEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"QPlainTextEdit {\n"
"    background-color: rgb(27, 29, 35);\n"
"    border-radius: 5px;\n"
"    padding: 10px;\n"
"    selection-color: rgb(255, 255, 255);\n"
"    selection-background-color: rgb(255, 121, 198);\n"
"}\n"
"QPlainTextEdit  QScrollBar:vertical {\n"
"    width: 8px;\n"
" }\n"
"QPlainTextEdit  QScrollBar:horizontal {\n"
"    height: 8px;\n"
" }\n"
"QPlainTextEdit:hover {\n"
"    border: 2px solid rgb(64, 71, 88);\n"
"}\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid rgb(91, 101, 124);\n"
"}\n"
"\n"
"QScrollBar:horizontal {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    height: 13px;\n"
"    margin: 0px 21px 0 21px;\n"
"    border-radius: 0px;\n"
"}\n"
"QScrollBar::handle:horizontal {\n"
"    background: rgb(189, 147, 249);\n"
"    min-width: 25px;\n"
"    border-radius: 4px\n"
"}\n"
"QScrollBar::add-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-right-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"    subcontrol-position: right;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::sub-line:horizontal {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"    width: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-bottom-left-radius: 4px;\n"
"    subcontrol-position: left;\n"
"    subcontrol-origin: margin;\n"
"}\n"
"QScrollBar::up-arrow:horizontal, QScrollBar::down-arrow:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
"QScrollBar::add-page:horizontal, QScrollBar::sub-page:horizontal\n"
"{\n"
"     background: none;\n"
"}\n"
" QScrollBar:vertical {\n"
"    border: none;\n"
"    background: rgb(52, 59, 72);\n"
"    width: 13px;\n"
"    margin: 21px 0 21px 0;\n"
"    border-radius: 0px;\n"
" }\n"
" QScrollBar::handle:vertical {\n"
"    background: rgb(189, 147, 249);\n"
"    min-height: 25px;\n"
"    border-radius: 4px\n"
" }\n"
" QScrollBar::add-line:vertical {\n"
"     border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-bottom-left-radius: 4px;\n"
"    border-bottom-right-radius: 4px;\n"
"     subcontrol-position: bottom;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::sub-line:vertical {\n"
"    border: none;\n"
"    background: rgb(55, 63, 77);\n"
"     height: 20px;\n"
"    border-top-left-radius: 4px;\n"
"    border-top-right-radius: 4px;\n"
"     subcontrol-position: top;\n"
"     subcontrol-origin: margin;\n"
" }\n"
" QScrollBar::up-arrow:vertical, QScrollBar::down-arrow:vertical {\n"
"     background: none;\n"
" }\n"
" QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"     background: none;\n"
" }\n"
"\n"
"")
        self.styleSheet.setObjectName("styleSheet")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.styleSheet)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.bgApp = QtWidgets.QFrame(parent=self.styleSheet)
        self.bgApp.setStyleSheet("#bgApp {\n"
"    background-color: rgb(40, 44, 52);\n"
"    border: 1px solid rgb(44, 49, 58);\n"
"}")
        self.bgApp.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.bgApp.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.bgApp.setObjectName("bgApp")
        self.appLayout = QtWidgets.QHBoxLayout(self.bgApp)
        self.appLayout.setContentsMargins(0, 0, 0, 0)
        self.appLayout.setSpacing(0)
        self.appLayout.setObjectName("appLayout")
        self.leftMenuBg = QtWidgets.QFrame(parent=self.bgApp)
        self.leftMenuBg.setMinimumSize(QtCore.QSize(60, 0))
        self.leftMenuBg.setMaximumSize(QtCore.QSize(60, 16777215))
        self.leftMenuBg.setStyleSheet("#leftMenuBg {\n"
"    background-color: rgb(33, 37, 43);\n"
"}")
        self.leftMenuBg.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.leftMenuBg.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftMenuBg.setObjectName("leftMenuBg")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.leftMenuBg)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.topLogoInfo = QtWidgets.QFrame(parent=self.leftMenuBg)
        self.topLogoInfo.setMinimumSize(QtCore.QSize(0, 50))
        self.topLogoInfo.setMaximumSize(QtCore.QSize(16777215, 50))
        self.topLogoInfo.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.topLogoInfo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.topLogoInfo.setObjectName("topLogoInfo")
        self.topLogo = QtWidgets.QFrame(parent=self.topLogoInfo)
        self.topLogo.setGeometry(QtCore.QRect(10, 5, 42, 42))
        self.topLogo.setMinimumSize(QtCore.QSize(42, 42))
        self.topLogo.setMaximumSize(QtCore.QSize(42, 42))
        self.topLogo.setStyleSheet("#topLogo {\n"
"    background-color: rgb(33, 37, 43);\n"
"    background-image: url(:/images/images/images/Amazon-PNG-File.png);\n"
"    background-position: centered;\n"
"    background-repeat: no-repeat;\n"
"}")
        self.topLogo.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.topLogo.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.topLogo.setObjectName("topLogo")
        self.verticalLayout_3.addWidget(self.topLogoInfo)
        self.leftMenuFrame = QtWidgets.QFrame(parent=self.leftMenuBg)
        self.leftMenuFrame.setStyleSheet("#leftMenuFrame{\n"
"    border-top: 3px solid rgb(44, 49, 58);\n"
"}")
        self.leftMenuFrame.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.leftMenuFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftMenuFrame.setObjectName("leftMenuFrame")
        self.verticalMenuLayout = QtWidgets.QVBoxLayout(self.leftMenuFrame)
        self.verticalMenuLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalMenuLayout.setSpacing(0)
        self.verticalMenuLayout.setObjectName("verticalMenuLayout")
        self.toggleBox = QtWidgets.QFrame(parent=self.leftMenuFrame)
        self.toggleBox.setMaximumSize(QtCore.QSize(16777215, 45))
        self.toggleBox.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.toggleBox.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.toggleBox.setObjectName("toggleBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.toggleBox)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toggleButton = QtWidgets.QPushButton(parent=self.toggleBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.toggleButton.sizePolicy().hasHeightForWidth())
        self.toggleButton.setSizePolicy(sizePolicy)
        self.toggleButton.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.toggleButton.setFont(font)
        self.toggleButton.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.toggleButton.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.toggleButton.setStyleSheet("#toggleButton {\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 20px solid transparent;\n"
"    background-image: url(:/icons/images/icons/icon_menu.png);\n"
"    background-color: rgb(37, 41, 48);\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"    color: rgb(113, 126, 149);\n"
"}\n"
"#toggleButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#toggleButton:pressed {\n"
"    background-color: rgb(189, 147, 249);\n"
"}\n"
"\n"
"")
        self.toggleButton.setObjectName("toggleButton")
        self.verticalLayout_4.addWidget(self.toggleButton)
        self.verticalMenuLayout.addWidget(self.toggleBox)
        self.topMenu = QtWidgets.QFrame(parent=self.leftMenuFrame)
        self.topMenu.setStyleSheet("#topMenu QPushButton {\n"
"    background-position: left center;\n"
"    background-repeat: no-repeat;\n"
"    border: none;\n"
"    border-left: 22px solid transparent;\n"
"    background-color: transparent;\n"
"    text-align: left;\n"
"    padding-left: 44px;\n"
"}\n"
"#topMenu QPushButton:hover {\n"
"    background-color: rgb(40, 44, 52);\n"
"}\n"
"#topMenu QPushButton:pressed {\n"
"    background-color: rgb(189, 147, 249);\n"
"    color: rgb(255, 255, 255);\n"
"}")
        self.topMenu.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.topMenu.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.topMenu.setObjectName("topMenu")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.topMenu)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.btn_home = QtWidgets.QPushButton(parent=self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_home.sizePolicy().hasHeightForWidth())
        self.btn_home.setSizePolicy(sizePolicy)
        self.btn_home.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.btn_home.setFont(font)
        self.btn_home.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_home.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_home.setStyleSheet("background-image: url(:/icons/images/icons/cil-home.png);")
        self.btn_home.setObjectName("btn_home")
        self.verticalLayout_8.addWidget(self.btn_home)
        self.btn_widgets = QtWidgets.QPushButton(parent=self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_widgets.sizePolicy().hasHeightForWidth())
        self.btn_widgets.setSizePolicy(sizePolicy)
        self.btn_widgets.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.btn_widgets.setFont(font)
        self.btn_widgets.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_widgets.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_widgets.setStyleSheet("background-image: url(:/icons/images/icons/cil-folder-open.png);")
        self.btn_widgets.setObjectName("btn_widgets")
        self.verticalLayout_8.addWidget(self.btn_widgets)
        self.btn_new = QtWidgets.QPushButton(parent=self.topMenu)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_new.sizePolicy().hasHeightForWidth())
        self.btn_new.setSizePolicy(sizePolicy)
        self.btn_new.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.btn_new.setFont(font)
        self.btn_new.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_new.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_new.setStyleSheet("background-image: url(:/icons/images/icons/cil-file.png);")
        self.btn_new.setObjectName("btn_new")
        self.verticalLayout_8.addWidget(self.btn_new)
        self.btn_botPage = QtWidgets.QPushButton(parent=self.topMenu)
        self.btn_botPage.setMinimumSize(QtCore.QSize(0, 45))
        self.btn_botPage.setStyleSheet("background-image:url(:/icons/images/icons/cil-user.png)")
        self.btn_botPage.setObjectName("btn_botPage")
        self.verticalLayout_8.addWidget(self.btn_botPage)
        self.verticalMenuLayout.addWidget(self.topMenu, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_3.addWidget(self.leftMenuFrame)
        self.appLayout.addWidget(self.leftMenuBg)
        self.contentBox = QtWidgets.QFrame(parent=self.bgApp)
        self.contentBox.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.contentBox.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.contentBox.setObjectName("contentBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.contentBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.contentTopBg = QtWidgets.QFrame(parent=self.contentBox)
        self.contentTopBg.setMinimumSize(QtCore.QSize(0, 50))
        self.contentTopBg.setMaximumSize(QtCore.QSize(16777215, 50))
        self.contentTopBg.setStyleSheet("#contentTopBg{\n"
"    background-color: rgb(33, 37, 43);\n"
"}")
        self.contentTopBg.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.contentTopBg.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.contentTopBg.setObjectName("contentTopBg")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.contentTopBg)
        self.horizontalLayout.setContentsMargins(0, 0, 10, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.leftBox = QtWidgets.QFrame(parent=self.contentTopBg)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.leftBox.sizePolicy().hasHeightForWidth())
        self.leftBox.setSizePolicy(sizePolicy)
        self.leftBox.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.leftBox.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.leftBox.setObjectName("leftBox")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.leftBox)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.titleRightInfo = QtWidgets.QLabel(parent=self.leftBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.titleRightInfo.sizePolicy().hasHeightForWidth())
        self.titleRightInfo.setSizePolicy(sizePolicy)
        self.titleRightInfo.setMaximumSize(QtCore.QSize(16777215, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(20)
        font.setBold(True)
        font.setItalic(False)
        self.titleRightInfo.setFont(font)
        self.titleRightInfo.setStyleSheet("#titleRightInfo { padding-left: 10px;\n"
"    font: 700 20pt \"Segoe Print\";\n"
" }")
        self.titleRightInfo.setAlignment(QtCore.Qt.AlignmentFlag.AlignLeading|QtCore.Qt.AlignmentFlag.AlignLeft|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.titleRightInfo.setObjectName("titleRightInfo")
        self.horizontalLayout_3.addWidget(self.titleRightInfo)
        self.horizontalLayout.addWidget(self.leftBox)
        self.rightButtons = QtWidgets.QFrame(parent=self.contentTopBg)
        self.rightButtons.setMinimumSize(QtCore.QSize(0, 28))
        self.rightButtons.setStyleSheet("#rightButtons .QPushButton { background-color: rgba(255, 255, 255, 0); border: none;  border-radius: 5px; }\n"
"#rightButtons .QPushButton:hover { background-color: rgb(44, 49, 57); border-style: solid; border-radius: 4px; }\n"
"#rightButtons .QPushButton:pressed { background-color: rgb(23, 26, 30); border-style: solid; border-radius: 4px; }")
        self.rightButtons.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.rightButtons.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.rightButtons.setObjectName("rightButtons")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.rightButtons)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(5)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.settingsTopBtn = QtWidgets.QPushButton(parent=self.rightButtons)
        self.settingsTopBtn.setEnabled(True)
        self.settingsTopBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.settingsTopBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.settingsTopBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.settingsTopBtn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_settings.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.settingsTopBtn.setIcon(icon)
        self.settingsTopBtn.setIconSize(QtCore.QSize(20, 20))
        self.settingsTopBtn.setObjectName("settingsTopBtn")
        self.horizontalLayout_2.addWidget(self.settingsTopBtn)
        self.minimizeAppBtn = QtWidgets.QPushButton(parent=self.rightButtons)
        self.minimizeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.minimizeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.minimizeAppBtn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_minimize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.minimizeAppBtn.setIcon(icon1)
        self.minimizeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.minimizeAppBtn.setObjectName("minimizeAppBtn")
        self.horizontalLayout_2.addWidget(self.minimizeAppBtn)
        self.maximizeRestoreAppBtn = QtWidgets.QPushButton(parent=self.rightButtons)
        self.maximizeRestoreAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.maximizeRestoreAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        font.setStyleStrategy(QtGui.QFont.StyleStrategy.PreferDefault)
        self.maximizeRestoreAppBtn.setFont(font)
        self.maximizeRestoreAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.maximizeRestoreAppBtn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_maximize.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.maximizeRestoreAppBtn.setIcon(icon2)
        self.maximizeRestoreAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.maximizeRestoreAppBtn.setObjectName("maximizeRestoreAppBtn")
        self.horizontalLayout_2.addWidget(self.maximizeRestoreAppBtn)
        self.closeAppBtn = QtWidgets.QPushButton(parent=self.rightButtons)
        self.closeAppBtn.setMinimumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setMaximumSize(QtCore.QSize(28, 28))
        self.closeAppBtn.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.closeAppBtn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/icons/images/icons/icon_close.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.closeAppBtn.setIcon(icon3)
        self.closeAppBtn.setIconSize(QtCore.QSize(20, 20))
        self.closeAppBtn.setObjectName("closeAppBtn")
        self.horizontalLayout_2.addWidget(self.closeAppBtn)
        self.horizontalLayout.addWidget(self.rightButtons, 0, QtCore.Qt.AlignmentFlag.AlignRight)
        self.verticalLayout_2.addWidget(self.contentTopBg)
        self.contentBottom = QtWidgets.QFrame(parent=self.contentBox)
        self.contentBottom.setStyleSheet("#contentBottom{\n"
"    border-top: 3px solid rgb(44, 49, 58);\n"
"}")
        self.contentBottom.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.contentBottom.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.contentBottom.setObjectName("contentBottom")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.contentBottom)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.content = QtWidgets.QFrame(parent=self.contentBottom)
        self.content.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.content.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.content.setObjectName("content")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.content)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.frame_2 = QtWidgets.QFrame(parent=self.content)
        self.frame_2.setStyleSheet("#pagesContainer QPushButton {\n"
"    border: 2px solid rgb(52, 59, 72);\n"
"    border-radius: 5px;\n"
"    background-color: rgb(52, 59, 72);\n"
"}\n"
"#pagesContainer QPushButton:hover {\n"
"    background-color: rgb(57, 65, 80);\n"
"    border: 2px solid rgb(61, 70, 86);\n"
"}\n"
"#pagesContainer QPushButton:pressed {\n"
"    background-color: rgb(35, 40, 49);\n"
"    border: 2px solid rgb(43, 50, 61);\n"
"}\n"
"")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_15.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.stackedWidget = QtWidgets.QStackedWidget(parent=self.frame_2)
        self.stackedWidget.setStyleSheet("background: transparent;")
        self.stackedWidget.setObjectName("stackedWidget")
        self.home = QtWidgets.QWidget()
        self.home.setStyleSheet("background-image: url(:/images/images/images/rsz_pngegg.png);\n"
"background-position: center;\n"
"background-repeat: no-repeat;")
        self.home.setObjectName("home")
        self.stackedWidget.addWidget(self.home)
        self.botPage = QtWidgets.QWidget()
        self.botPage.setObjectName("botPage")
        self.tabWidget = QtWidgets.QTabWidget(parent=self.botPage)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 1111, 631))
        self.tabWidget.setStyleSheet("QTabWidget::pane {\n"
"  border-top: 1px solid rgb(147, 147, 147);\n"
"  top: 0px; \n"
"  background: rgb(40, 44, 52);\n"
"  \n"
"} \n"
"\n"
"QTabBar::tab {\n"
"  background-color: rgb(33, 37, 43);; \n"
"  padding: 8px;\n"
"} \n"
"\n"
"QTabBar::tab:selected { \n"
"  background: rgb(40, 44, 52); \n"
"  border-left: 1px solid rgb(147, 147, 147);\n"
"border-right: 1px solid rgb(147, 147, 147);\n"
"border-top: 1px solid rgb(147, 147, 147);\n"
"}\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.tabWidget.addTab(self.tab_5, "")
        self.stackedWidget.addWidget(self.botPage)
        self.createPage = QtWidgets.QWidget()
        self.createPage.setMaximumSize(QtCore.QSize(987, 627))
        self.createPage.setObjectName("createPage")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.createPage)
        self.gridLayout_2.setContentsMargins(0, 10, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(parent=self.createPage)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.frame_4 = QtWidgets.QFrame(parent=self.createPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_4.sizePolicy().hasHeightForWidth())
        self.frame_4.setSizePolicy(sizePolicy)
        self.frame_4.setMinimumSize(QtCore.QSize(300, 700))
        self.frame_4.setMaximumSize(QtCore.QSize(319, 609))
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_2.addWidget(self.frame_4, 1, 2, 1, 1)
        self.frame = QtWidgets.QFrame(parent=self.createPage)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame.sizePolicy().hasHeightForWidth())
        self.frame.setSizePolicy(sizePolicy)
        self.frame.setMaximumSize(QtCore.QSize(600, 16777215))
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.layoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(0, 30, 357, 630))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setVerticalSpacing(15)
        self.formLayout.setObjectName("formLayout")
        self.nameLine = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.nameLine.setMinimumSize(QtCore.QSize(219, 0))
        self.nameLine.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.nameLine.setInputMask("")
        self.nameLine.setText("")
        self.nameLine.setObjectName("nameLine")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.ItemRole.LabelRole, self.nameLine)
        self.addressLine = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.addressLine.setMinimumSize(QtCore.QSize(219, 0))
        self.addressLine.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.addressLine.setInputMask("")
        self.addressLine.setText("")
        self.addressLine.setObjectName("addressLine")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.ItemRole.LabelRole, self.addressLine)
        self.emailLine = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.emailLine.setMinimumSize(QtCore.QSize(219, 0))
        self.emailLine.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.emailLine.setInputMask("")
        self.emailLine.setText("")
        self.emailLine.setObjectName("emailLine")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.ItemRole.LabelRole, self.emailLine)
        self.passwordLine = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.passwordLine.setMinimumSize(QtCore.QSize(219, 0))
        self.passwordLine.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.passwordLine.setInputMask("")
        self.passwordLine.setText("")
        self.passwordLine.setObjectName("passwordLine")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.LabelRole, self.passwordLine)
        self.proxyLine = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.proxyLine.setMinimumSize(QtCore.QSize(219, 0))
        self.proxyLine.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.proxyLine.setInputMask("")
        self.proxyLine.setText("")
        self.proxyLine.setObjectName("proxyLine")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.LabelRole, self.proxyLine)
        self.portLine = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.portLine.setMinimumSize(QtCore.QSize(219, 0))
        self.portLine.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.portLine.setInputMask("")
        self.portLine.setText("")
        self.portLine.setObjectName("portLine")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.LabelRole, self.portLine)
        self.pathLine = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.pathLine.setMinimumSize(QtCore.QSize(219, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.pathLine.setFont(font)
        self.pathLine.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.pathLine.setInputMask("")
        self.pathLine.setText("")
        self.pathLine.setObjectName("pathLine")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.LabelRole, self.pathLine)
        self.btn_path = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_path.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.btn_path.setFont(font)
        self.btn_path.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_path.setStyleSheet("background-color: rgb(52, 59, 72);")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/icons/images/icons/cil-folder-open.png"), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.btn_path.setIcon(icon4)
        self.btn_path.setObjectName("btn_path")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.ItemRole.LabelRole, self.btn_path)
        self.btn_create = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_create.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.btn_create.setFont(font)
        self.btn_create.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_create.setStyleSheet("background-color: rgb(52, 59, 72);")
        self.btn_create.setObjectName("btn_create")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.ItemRole.LabelRole, self.btn_create)
        self.widget_2 = QtWidgets.QWidget(parent=self.layoutWidget)
        self.widget_2.setObjectName("widget_2")
        self.pathLine_2 = QtWidgets.QLineEdit(parent=self.widget_2)
        self.pathLine_2.setGeometry(QtCore.QRect(10, 30, 219, 34))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.pathLine_2.setFont(font)
        self.pathLine_2.setStyleSheet("background-color: rgb(33, 37, 43);")
        self.pathLine_2.setInputMask("")
        self.pathLine_2.setText("")
        self.pathLine_2.setObjectName("pathLine_2")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.ItemRole.LabelRole, self.widget_2)
        self.btn_PassSave = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_PassSave.setMinimumSize(QtCore.QSize(130, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.btn_PassSave.setFont(font)
        self.btn_PassSave.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_PassSave.setStyleSheet("background-color: rgb(52, 59, 72);")
        self.btn_PassSave.setObjectName("btn_PassSave")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.ItemRole.FieldRole, self.btn_PassSave)
        self.btn_ProxySave = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_ProxySave.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.btn_ProxySave.setFont(font)
        self.btn_ProxySave.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_ProxySave.setStyleSheet("background-color: rgb(52, 59, 72);")
        self.btn_ProxySave.setObjectName("btn_ProxySave")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.ItemRole.FieldRole, self.btn_ProxySave)
        self.btn_PortSave = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_PortSave.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.btn_PortSave.setFont(font)
        self.btn_PortSave.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_PortSave.setStyleSheet("background-color: rgb(52, 59, 72);")
        self.btn_PortSave.setObjectName("btn_PortSave")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.ItemRole.FieldRole, self.btn_PortSave)
        self.btn_PathSave = QtWidgets.QPushButton(parent=self.layoutWidget)
        self.btn_PathSave.setMinimumSize(QtCore.QSize(120, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.btn_PathSave.setFont(font)
        self.btn_PathSave.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_PathSave.setStyleSheet("background-color: rgb(52, 59, 72);")
        self.btn_PathSave.setObjectName("btn_PathSave")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.ItemRole.FieldRole, self.btn_PathSave)
        self.gridLayout_2.addWidget(self.frame, 1, 0, 1, 1)
        self.stackedWidget.addWidget(self.createPage)
        self.widgets = QtWidgets.QWidget()
        self.widgets.setStyleSheet("b")
        self.widgets.setObjectName("widgets")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widgets)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setObjectName("verticalLayout")
        self.row_1 = QtWidgets.QFrame(parent=self.widgets)
        self.row_1.setMinimumSize(QtCore.QSize(0, 30))
        self.row_1.setMaximumSize(QtCore.QSize(16777215, 70))
        self.row_1.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.row_1.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.row_1.setObjectName("row_1")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.row_1)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.label_2 = QtWidgets.QLabel(parent=self.row_1)
        self.label_2.setIndent(-1)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_16.addWidget(self.label_2)
        self.verticalLayout.addWidget(self.row_1)
        self.widget = QtWidgets.QWidget(parent=self.widgets)
        self.widget.setMinimumSize(QtCore.QSize(0, 60))
        self.widget.setObjectName("widget")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.frame_3 = QtWidgets.QFrame(parent=self.widget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.horizontalLayout_6.addWidget(self.frame_3)
        self.databaseButtons = QtWidgets.QFrame(parent=self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.databaseButtons.sizePolicy().hasHeightForWidth())
        self.databaseButtons.setSizePolicy(sizePolicy)
        self.databaseButtons.setMinimumSize(QtCore.QSize(100, 0))
        self.databaseButtons.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.databaseButtons.setStyleSheet("#databaseButtons QPushButton{\n"
"    background-color: rgb(52, 59, 72);\n"
"}")
        self.databaseButtons.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.databaseButtons.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.databaseButtons.setObjectName("databaseButtons")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.databaseButtons)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setSpacing(6)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.btn_loadFromDB = QtWidgets.QPushButton(parent=self.databaseButtons)
        self.btn_loadFromDB.setObjectName("btn_loadFromDB")
        self.horizontalLayout_7.addWidget(self.btn_loadFromDB)
        self.btn_addToDB = QtWidgets.QPushButton(parent=self.databaseButtons)
        self.btn_addToDB.setObjectName("btn_addToDB")
        self.horizontalLayout_7.addWidget(self.btn_addToDB)
        self.btn_deleteFromDB = QtWidgets.QPushButton(parent=self.databaseButtons)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_deleteFromDB.sizePolicy().hasHeightForWidth())
        self.btn_deleteFromDB.setSizePolicy(sizePolicy)
        self.btn_deleteFromDB.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.btn_deleteFromDB.setFont(font)
        self.btn_deleteFromDB.setStyleSheet("background-color: rgb(52, 59, 72);")
        self.btn_deleteFromDB.setIconSize(QtCore.QSize(16, 16))
        self.btn_deleteFromDB.setObjectName("btn_deleteFromDB")
        self.horizontalLayout_7.addWidget(self.btn_deleteFromDB)
        self.horizontalLayout_6.addWidget(self.databaseButtons)
        self.verticalLayout.addWidget(self.widget)
        self.row_3 = QtWidgets.QFrame(parent=self.widgets)
        self.row_3.setMinimumSize(QtCore.QSize(0, 120))
        self.row_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.row_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.row_3.setObjectName("row_3")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.row_3)
        self.horizontalLayout_12.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_12.setSpacing(0)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.row_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Active, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Inactive, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.NoBrush)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0, 0))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(221, 221, 221, 128))
        brush.setStyle(QtCore.Qt.BrushStyle.SolidPattern)
        palette.setBrush(QtGui.QPalette.ColorGroup.Disabled, QtGui.QPalette.ColorRole.PlaceholderText, brush)
        self.tableWidget.setPalette(palette)
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.tableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarPolicy.ScrollBarAlwaysOn)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.SizeAdjustPolicy.AdjustToContents)
        self.tableWidget.setAutoScroll(False)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.EditTrigger.NoEditTriggers)
        self.tableWidget.setSelectionMode(QtWidgets.QAbstractItemView.SelectionMode.SingleSelection)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectionBehavior.SelectRows)
        self.tableWidget.setShowGrid(True)
        self.tableWidget.setGridStyle(QtCore.Qt.PenStyle.SolidLine)
        self.tableWidget.setColumnCount(8)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setRowCount(16)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        item.setFont(font)
        self.tableWidget.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(8, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(9, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(10, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(11, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(12, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(13, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(14, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setVerticalHeaderItem(15, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        self.tableWidget.horizontalHeader().setVisible(True)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(True)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setCascadingSectionResizes(False)
        self.tableWidget.verticalHeader().setHighlightSections(False)
        self.tableWidget.verticalHeader().setStretchLastSection(True)
        self.horizontalLayout_12.addWidget(self.tableWidget)
        self.verticalLayout.addWidget(self.row_3)
        self.stackedWidget.addWidget(self.widgets)
        self.verticalLayout_15.addWidget(self.stackedWidget)
        self.horizontalLayout_4.addWidget(self.frame_2)
        self.extraRightBox = QtWidgets.QFrame(parent=self.content)
        self.extraRightBox.setMinimumSize(QtCore.QSize(0, 0))
        self.extraRightBox.setMaximumSize(QtCore.QSize(0, 16777215))
        self.extraRightBox.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.extraRightBox.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.extraRightBox.setObjectName("extraRightBox")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.extraRightBox)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(0)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.themeSettingsTopDetail = QtWidgets.QFrame(parent=self.extraRightBox)
        self.themeSettingsTopDetail.setMaximumSize(QtCore.QSize(16777215, 3))
        self.themeSettingsTopDetail.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.themeSettingsTopDetail.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.themeSettingsTopDetail.setObjectName("themeSettingsTopDetail")
        self.verticalLayout_7.addWidget(self.themeSettingsTopDetail)
        self.contentSettings = QtWidgets.QFrame(parent=self.extraRightBox)
        self.contentSettings.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.contentSettings.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.contentSettings.setObjectName("contentSettings")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.contentSettings)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.topMenus = QtWidgets.QFrame(parent=self.contentSettings)
        self.topMenus.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.topMenus.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.topMenus.setObjectName("topMenus")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.topMenus)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.btn_message = QtWidgets.QPushButton(parent=self.topMenus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_message.sizePolicy().hasHeightForWidth())
        self.btn_message.setSizePolicy(sizePolicy)
        self.btn_message.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.btn_message.setFont(font)
        self.btn_message.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_message.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_message.setStyleSheet("background-image: url(:/icons/images/icons/cil-envelope-open.png);")
        self.btn_message.setObjectName("btn_message")
        self.verticalLayout_14.addWidget(self.btn_message)
        self.btn_print = QtWidgets.QPushButton(parent=self.topMenus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_print.sizePolicy().hasHeightForWidth())
        self.btn_print.setSizePolicy(sizePolicy)
        self.btn_print.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.btn_print.setFont(font)
        self.btn_print.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_print.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_print.setStyleSheet("background-image: url(:/icons/images/icons/cil-print.png);")
        self.btn_print.setObjectName("btn_print")
        self.verticalLayout_14.addWidget(self.btn_print)
        self.btn_logout = QtWidgets.QPushButton(parent=self.topMenus)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btn_logout.sizePolicy().hasHeightForWidth())
        self.btn_logout.setSizePolicy(sizePolicy)
        self.btn_logout.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(False)
        self.btn_logout.setFont(font)
        self.btn_logout.setCursor(QtGui.QCursor(QtCore.Qt.CursorShape.PointingHandCursor))
        self.btn_logout.setLayoutDirection(QtCore.Qt.LayoutDirection.LeftToRight)
        self.btn_logout.setStyleSheet("background-image: url(:/icons/images/icons/cil-account-logout.png);")
        self.btn_logout.setObjectName("btn_logout")
        self.verticalLayout_14.addWidget(self.btn_logout)
        self.verticalLayout_13.addWidget(self.topMenus, 0, QtCore.Qt.AlignmentFlag.AlignTop)
        self.verticalLayout_7.addWidget(self.contentSettings)
        self.horizontalLayout_4.addWidget(self.extraRightBox)
        self.verticalLayout_6.addWidget(self.content)
        self.bottomBar = QtWidgets.QFrame(parent=self.contentBottom)
        self.bottomBar.setMinimumSize(QtCore.QSize(0, 22))
        self.bottomBar.setMaximumSize(QtCore.QSize(16777215, 22))
        self.bottomBar.setStyleSheet("#bottomBar { background-color: rgb(44, 49, 58); }\n"
"#bottomBar QLabel { font-size: 11px; color: rgb(113, 126, 149); padding-left: 10px; padding-right: 10px; padding-bottom: 2px; }")
        self.bottomBar.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.bottomBar.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.bottomBar.setObjectName("bottomBar")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.bottomBar)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.creditsLabel = QtWidgets.QLabel(parent=self.bottomBar)
        self.creditsLabel.setMaximumSize(QtCore.QSize(16777215, 16))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(-1)
        font.setBold(True)
        font.setItalic(False)
        self.creditsLabel.setFont(font)
        self.creditsLabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignRight|QtCore.Qt.AlignmentFlag.AlignTrailing|QtCore.Qt.AlignmentFlag.AlignVCenter)
        self.creditsLabel.setObjectName("creditsLabel")
        self.horizontalLayout_5.addWidget(self.creditsLabel)
        self.frame_size_grip = QtWidgets.QFrame(parent=self.bottomBar)
        self.frame_size_grip.setMinimumSize(QtCore.QSize(20, 0))
        self.frame_size_grip.setMaximumSize(QtCore.QSize(20, 16777215))
        self.frame_size_grip.setFrameShape(QtWidgets.QFrame.Shape.NoFrame)
        self.frame_size_grip.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_size_grip.setObjectName("frame_size_grip")
        self.horizontalLayout_5.addWidget(self.frame_size_grip)
        self.verticalLayout_6.addWidget(self.bottomBar)
        self.verticalLayout_2.addWidget(self.contentBottom)
        self.appLayout.addWidget(self.contentBox)
        self.horizontalLayout_8.addWidget(self.bgApp)
        MainWindow.setCentralWidget(self.styleSheet)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toggleButton.setText(_translate("MainWindow", "Hide"))
        self.btn_home.setText(_translate("MainWindow", "Home"))
        self.btn_widgets.setText(_translate("MainWindow", "Database"))
        self.btn_new.setText(_translate("MainWindow", "New"))
        self.btn_botPage.setText(_translate("MainWindow", "PushButton"))
        self.titleRightInfo.setText(_translate("MainWindow", "Amazon BOT"))
        self.settingsTopBtn.setToolTip(_translate("MainWindow", "Settings"))
        self.minimizeAppBtn.setToolTip(_translate("MainWindow", "Minimize"))
        self.maximizeRestoreAppBtn.setToolTip(_translate("MainWindow", "Maximize"))
        self.closeAppBtn.setToolTip(_translate("MainWindow", "Close"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("MainWindow", "Tab 1"))
        self.label.setText(_translate("MainWindow", "CREATE BROWSER PROFILE"))
        self.nameLine.setPlaceholderText(_translate("MainWindow", "Imie i nazwisko"))
        self.addressLine.setPlaceholderText(_translate("MainWindow", "Adres"))
        self.emailLine.setPlaceholderText(_translate("MainWindow", "Email"))
        self.passwordLine.setPlaceholderText(_translate("MainWindow", "Password"))
        self.proxyLine.setPlaceholderText(_translate("MainWindow", "Proxy"))
        self.portLine.setPlaceholderText(_translate("MainWindow", "Port"))
        self.pathLine.setPlaceholderText(_translate("MainWindow", "Path"))
        self.btn_path.setText(_translate("MainWindow", "Choose Path"))
        self.btn_create.setText(_translate("MainWindow", "CREATE"))
        self.pathLine_2.setPlaceholderText(_translate("MainWindow", "Path"))
        self.btn_PassSave.setText(_translate("MainWindow", "SAVE/UNSAVE"))
        self.btn_ProxySave.setText(_translate("MainWindow", "SAVE/UNSAVE"))
        self.btn_PortSave.setText(_translate("MainWindow", "SAVE/UNSAVE"))
        self.btn_PathSave.setText(_translate("MainWindow", "SAVE/UNSAVE"))
        self.label_2.setText(_translate("MainWindow", "BAZA DANYCH"))
        self.btn_loadFromDB.setText(_translate("MainWindow", "QUICK LOAD"))
        self.btn_addToDB.setText(_translate("MainWindow", "LOAD"))
        self.btn_deleteFromDB.setText(_translate("MainWindow", "DELETE"))
        self.tableWidget.setSortingEnabled(False)
        item = self.tableWidget.verticalHeaderItem(0)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(1)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(2)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(3)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(4)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(5)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(6)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(7)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(8)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(9)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(10)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(11)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(12)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(13)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(14)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.verticalHeaderItem(15)
        item.setText(_translate("MainWindow", "New Row"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "1"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "2"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "3"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "4"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "5"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "6"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("MainWindow", "7"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("MainWindow", "8"))
        self.btn_message.setText(_translate("MainWindow", "Message"))
        self.btn_print.setText(_translate("MainWindow", "Print"))
        self.btn_logout.setText(_translate("MainWindow", "Logout"))
        self.creditsLabel.setText(_translate("MainWindow", "By: Ignacy"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
